### PR TITLE
upgrade go version

### PR DESCRIPTION
**Pull request by temoto**

### CODE REVIEW

**Comment by temoto** [comment]
Seems to fix goimports.

**Comment by awalterschulze** [comment]
I think `1.x` is more stable than `tip` and gives you the newest released version.
So you can replace `1.8` with `1.x` and I think it should also fix the problem.

**Comment by temoto** [comment]
Thank you, I didn't know about 1.x alias.

**Comment by awalterschulze** [comment]
Oh I see, tip was there before.
Let's remove tip

**Comment by awalterschulze** [comment]
You don't need quotes

https://github.com/awalterschulze/goderive/blob/master/.travis.yml#L7

**Comment by awalterschulze** [comment]
Sorry for being so nit picky
I really appreciate the help in keeping this package up to date and stable

**Comment by awalterschulze** [comment]
Thank you so much :)

**Comment by temoto** [comment]
No worries mate, I like details too.

**Pull request merged**
