### PR TITLE
Fix isNumber to only accept numbers

### LINKED ISSUE #13: isNumber accepts non-numbers
isNumber in escape.go is supposed to return true if it is passed a string that represents a number. However, it accepts "127.0.0.1" as a number but dot does not accept that. More generally it allows an arbitrary number of "."s in a number. This causes strings to not be escaped when they should be.

### PR DESCRIPTION
**Pull request by drt24**
Fixes #13.

I am happy to give over my copyright on this change.

### CODE REVIEW

**Comment by awalterschulze** [comment]
Great :)

Maybe you would like to add your test case as well?

**Comment by awalterschulze** [comment]
Hello?

**Comment by drt24** [comment]
I am working on something  else at the moment, should come back to this in late October.

**Comment by awalterschulze** [comment]
Cool Thanks

**Comment by awalterschulze** [comment]
I would really love a test case that breaks the old code.

**Comment by k3ntaroo** [comment]
Hello.

`"."`, `"-."`, `"----."` are the cases accepted as numbers by the old code.

**Comment by awalterschulze** [comment]
Cool. Thank you very much. That is really helpful.

Now we just need someone to include those in a test case to make sure we
don't regress. And then we can merge this.

**Comment by awalterschulze** [comment]
No activity, so going to close.

**Pull request closed without merging**
