### PR TITLE
Passing in map[string]string as attributes can cause dot to fail

### PR DESCRIPTION
**Pull request by chewxy**
Mainly because users can pass in some misspelled things (like "lable" instead of "label"). 

To that effect, I've actually created and exposed a list of static Attributes that can be found here: http://www.graphviz.org/doc/info/attrs.html

### CODE REVIEW

**Comment by chewxy** [comment]
Hmm.. I just noticed #4. 

Do you want me to update the API in such a way that does not break backwards compat? (Also, Ammend is spelled wrongly)

**Comment by awalterschulze** [comment]
First off, very cool :)
I would really love to merge this.
I'll give it a better review soon.

Backwards compatibility might be important.
I'll ask the one user that is on the list of current users.

@smira What do you think about breaking backwards compatibility here, in favour of type safety?

**Comment by chewxy** [comment]
Nah. I'll withdraw this PR. I'll submit another one tomorrow morning without breaking backwards compat (and value types). Should really have checked the issues list first

**Comment by awalterschulze** [comment]
O ok, well, I look forward to it :)

**Pull request closed without merging**
