### PR TITLE
Allow subgraphs to be removed including nodes

### PR DESCRIPTION
**Pull request by ruudk**

### CODE REVIEW

**Comment by awalterschulze** [comment]
I can't remember.  Is there the possibility of having an edge to a subgraph?

**Comment by awalterschulze** [comment]
There is an error check fail on the commit

```go
errcheck -ignore 'fmt:[FS]?[Pp]rint*' ./...
graph.go:158:15:	g.RemoveNode(parentGraph, child)
```

**Comment by ruudk** [comment]
> I can't remember. Is there the possibility of having an edge to a subgraph?

How would that work? Like this?
```golang
    if err := g.AddSubGraph("G", "cluster_FooBar", nil); err != nil {
		t.Fatal(err)
	}
	if err := g.AddEdge("Hello", "cluster_FooBar", true, nil); err != nil {
		t.Fatal(err)
	}
```

**Comment by ruudk** [comment]
@awalterschulze what do you think? Anything I need to change?

**Comment by awalterschulze** [comment]
Sorry I am a bit busy with relocating to London.  I will look at this asap.
It is just hard to find some time to think of some edge cases for tests.

Btw ticketswap was very useful for selling a ticket for a concert I could no longer attend, because of this relocation.  Thank you so much :)

**Comment by ruudk** [comment]
No worries! Good luck with the relocation.

Great to hear you liked TS 🤗 Spread the word in London 🙏

**Comment by awalterschulze** [comment]
I finally arrived and got a second to think.

Sorry to say, but I have nothing of value to add, this looks perfect :)

Thank you so much for your work and patience.

**Comment by ruudk** [comment]
Thanks! Enjoy London!

**Pull request merged**
