### PR TITLE
Make cluster subgraphs as nodes for edges

### PR DESCRIPTION
**Pull request by Didainius**
There's an issue where making edges between cluster subgraphs (which are useful with fdp) would double subgraphs in output string.

Consider this code:
```go
g := gographviz.NewEscape()
g.SetName("G")
g.SetDir(false)
g.AddSubGraph("G", "cluster0", map[string]string{"label": "root"})
g.AddSubGraph("cluster0", "cluster_1", map[string]string{"label": "child 1"})
g.AddSubGraph("cluster0", "cluster_2", map[string]string{"label": "child 2"})
nodeStyle := map[string]string{"style": "rounded"}
g.AddNode("cluster_1", "1", nodeStyle)
g.AddNode("cluster_1", "2", nodeStyle)
g.AddNode("cluster_2", "3", nodeStyle)
g.AddNode("cluster_2", "4", nodeStyle)
g.AddNode("G", "Code deployment", map[string]string{"style": "dotted"})
g.AddPortEdge("cluster_2", "", "cluster_1", "", false, nil)
s := g.String()
fmt.Println(s)
```

It currently renders such code, which is incorrect and would not render:

graph G {
        subgraph cluster_2 {
        label="child 2";
        3 [ style=rounded ];
        4 [ style=rounded ];

}
**--subgraph cluster_1 {**
        label="child 1";
        1 [ style=rounded ];
        2 [ style=rounded ];

};
        subgraph cluster0 {
        label=root;
        subgraph cluster_1 {
        label="child 1";
        1 [ style=rounded ];
        2 [ style=rounded ];

}
;
        subgraph cluster_2 {
        label="child 2";
        3 [ style=rounded ];
        4 [ style=rounded ];

}
;

}
;
        "Code deployment" [ style=dotted ];

}

After the patch applied it would make such code (subgraphs starting with cluster would be rendered as nodes for edges):
graph G {
        **cluster_2--cluster_1;**
        subgraph cluster0 {
        label=root;
        subgraph cluster_1 {
        label="child 1";
        1 [ style=rounded ];
        2 [ style=rounded ];

}
;
        subgraph cluster_2 {
        label="child 2";
        3 [ style=rounded ];
        4 [ style=rounded ];

}
;

}
;
        "Code deployment" [ style=dotted ];

}

### CODE REVIEW

**Comment by awalterschulze** [comment]
Could you use your output to make a unit test?

**Comment by Didainius** [comment]
Here it is

**Comment by awalterschulze** [comment]
I think you might have found another bug.
gographviz is unable to parse this output

```
graph G {
	cluster_2--cluster_1;
	subgraph cluster0 {
	subgraph cluster_1 {

}
;
	subgraph cluster_2 {

}
;

}
;
	"Code deployment";

}
```

**Comment by awalterschulze** [comment]
I had to make some adjustments.
https://github.com/awalterschulze/gographviz/pull/22
What do you think?

**Comment by Didainius** [comment]
:thumbsup:

**Comment by awalterschulze** [comment]
Sorry the adjustments are here
https://github.com/awalterschulze/gographviz/pull/24

**Comment by awalterschulze** [comment]
I have merged the other pull request.

**Pull request closed without merging**
