### PR TITLE
Fix index out of range error

### PR DESCRIPTION
**Pull request by saheienko**
Fix index out of range error when use complex edge's port:
```graph.AddPortEdge("srcNode","srcPort:n","dstNode", "dstPort:w", true, nil)```

### CODE REVIEW

**Comment by awalterschulze** [comment]
Good catch :)

Could you add a unit test to make sure we don't regress?

**Comment by saheienko** [comment]
Yes, I'll add tests in a few days

**Comment by awalterschulze** [comment]
Thank you.  Looking forward to it.
I think a single unit test will be enough, but it is your call.

**Comment by saheienko** [comment]
Yeap, tests save the world :)

**Comment by awalterschulze** [comment]
Thank you so much.  Sorry for the delay.  I suddenly got really busy.

**Pull request merged**
