### PR TITLE
also sort graph edges when writing (resubmitting #72)

### PR DESCRIPTION
**Pull request by fenollp**
Overrides https://github.com/awalterschulze/gographviz/pull/72

### CODE REVIEW

**Comment by georgettica** [comment]
@awalterschulze ?

**Comment by awalterschulze** [comment]
Sorry I am on holiday, but I ran the  tests now, seems  there a few that should be easy to  fix.

**Comment by georgettica** [comment]
It's ok no probs, just wanted to loop you in aswell:)

**Comment by awalterschulze** [comment]
Thank you so much :)

**Pull request merged**
