### PR TITLE
Test for issue #32

### PR DESCRIPTION
**Pull request by nkitchen**
This test file contains the case I posted in the issue thread.

### CODE REVIEW

**Comment by awalterschulze** [comment]
Perfect thank you

**Comment by awalterschulze** [comment]
Do you want to contribute this fix in the pull request as well?

```diff
diff --git a/attrs.go b/attrs.go
index a00eeb7..5e1518a 100644
--- a/attrs.go
+++ b/attrs.go
@@ -56,9 +56,7 @@ func (attrs Attrs) Extend(more Attrs) {
 // Ammend only adds the missing attributes to attrs Attrs type.
 func (attrs Attrs) Ammend(more Attrs) {
        for key, value := range more {
-               if _, ok := attrs[key]; !ok {
-                       attrs.add(key, value)
-               }
+               attrs.add(key, value)
        }
 }
```

**Comment by nkitchen** [comment]
Your suggested fix just makes Ammend the same as Extend. Is that really what you intended?

**Comment by awalterschulze** [comment]
Good spot, yes maybe I just want to rather call extend and remove the ammend method.  I seems that ammend is not really what you ever want to do.

**Comment by nkitchen** [comment]
Yes, I came to basically the same conclusion after adding several more test cases. In fact, the proposed fix that I will send includes changing Nodes.Add to call Extend.

**Comment by awalterschulze** [comment]
Great work :)
I think this is ready to merge and you?

**Comment by nkitchen** [comment]
Yes, I believe this completely resolves the issue.

**Pull request merged**
