### PR TITLE
Fix GitHub actions build

### PR DESCRIPTION
**Pull request by jmrtt**
Update Github Actions to use environment files as described in #75.

### CODE REVIEW

**Comment by awalterschulze** [comment]
Thank you for fixing :D

**Comment by awalterschulze** [comment]
@jmrtt Have you added yourself to the AUTHORS file yet?

**Comment by jmrtt** [comment]
Not, did not think about that and it is not a problem. Next time :)

**Comment by awalterschulze** [comment]
Yeah anytime you want, just make a PR, I'll accept :)

**Pull request merged**
