### PR TITLE
Add some custom attributes 

### PR DESCRIPTION
**Pull request by frranck**

### CODE REVIEW

**Comment by awalterschulze** [comment]
I would like to avoid editing validAttrs as then the next caller of the
library is also affected

**Comment by frranck** [comment]
what about backing it up?

**Comment by frranck** [comment]
ps: any idea what the CI issue is?

**Comment by awalterschulze** [comment]
What about someone else calling the library concurrently to your call? I
don’t think backing up is going to work, sorry

**Comment by frranck** [comment]
> What about someone else calling the library concurrently to your call? I don’t think backing up is going to work, sorry

well we could put a mutex ;)

**Comment by awalterschulze** [comment]
haha
Technically
But maybe we can just try what I proposed before?

**Comment by frranck** [comment]
Sure, but I'm confused about what you want me to do.
You said _"We would need to inject it and make a new Analyse function that takes extra valid attrs or turns of valid attr checking."_
Isn't it what I just did with this new Analyse function?
If you want to turn off the "valid attr" checking you need a global variable, which leads to the same mutex over-engineering problem.

**Comment by awalterschulze** [comment]
Fair enough. That wasn’t very clear.

So starting with the analyse function the extra valid attrs would need to
be threaded all the way through to where the error checking happens.
Injecting the variable as an extra argument at every step to avoid touching
the global.

This is also not very clear, but I am on holiday.
I hope this hint helps explain why I think this might need to be a fork.

**Comment by frranck** [comment]
No worries,  enjoy your holidays

**Pull request closed without merging**
